services:
  server:
    build:
      context: .
    ports:
      - '8000:8000'

    volumes:
      - /Users/a.gazzaev/Desktop/BIG-DATA/lab1/classification_model/experiments/exp_25177033897488245161:/classification
      - /Users/a.gazzaev/Desktop/BIG-DATA/lab1/classification_model/data:/dataset

    extra_hosts:
      - host.docker.internal:host-gateway

  db:
   image: redis/redis-stack:latest

  
   command: redis-server --requirepass ${PASS}  --protected-mode yes

   ports:
      - '6379:6379'

  vault:
    image: vault:1.13.3
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
      - "8200:8200"
    environment:
      VAULT_ADDR: '${VAULT_ADDR}'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "127.0.0.1:8201","tls_disable":"1"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 1
    command: server -dev -dev-root-token-id='hvsvio2dl8SxHJU83uFk8O8JGGE'